In [4]:
# adding two matrices
x = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]
 
y = [[9,8,7],
    [6,5,4],
    [3,2,1]]
add = [[0,0,0],
      [0,0,0],
      [0,0,0]]
for i in range(len(x)):
        for j in range(len(x[0])):
            add[i][j] = x[i][j]    + y[i][j]
for a in add:
     print(a)

[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


In [7]:
# multiply two matrix
import numpy as np
x = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]
 
y = [[9,8,7],
    [6,5,4],
    [3,2,1]]
result= [[0,0,0],
      [0,0,0],
      [0,0,0]]
result = np.dot(x,y)
for r in result:
        print(r)


[30 24 18]
[84 69 54]
[138 114  90]


In [9]:
A = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]
  
# take a 3x4 matrix    
B = [[5, 8, 1, 2],
    [6, 7, 3, 0],
    [4, 5, 9, 1]]
      
result = [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]
  
# iterating by row of A
for i in range(len(A)):
  
    # iterating by coloum by B 
    for j in range(len(B[0])):
  
        # iterating by rows of B
        for k in range(len(B)):
            result[i][j] += A[i][k] * B[k][j]
  
 for r in result:
    print(r)
     A = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]
  
# take a 3x4 matrix    
B = [[5, 8, 1, 2],
    [6, 7, 3, 0],
    [4, 5, 9, 1]]
      
result = [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]
  for i in range(len(A)):
        for j in range(len(B[0])):
            for k in  range(len(B)):
                result+= A[i][k]+B[k][j]

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 24)

In [13]:
#def multiply(list):
  #  res = 1
 #   for i in list:
  #      res*= i
   # return res
list = [[1, 4, 5], [7, 3], [4], [46, 7, 3]]
#[int(i) for i  in input().split()]
#print(multiply(list))
list = [[1, 4, 5], [7, 3], [4], [46, 7, 3]]
for i in range(len(list)):
    for j in range(len(list[i])):
        res*=j

TypeError: can't multiply sequence by non-int of type 'list'

In [14]:
a=[[1,1],[1,1]]
b=[[1,1],[1,1]]
result=[[sum(i*j for i,j in zip(a_row,b_col))for b_col in zip(*b)]for a_row in a]

In [15]:
result

[[2, 2], [2, 2]]

In [5]:
# tranpose of a matrix
A = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]
import numpy as np
x = np.transpose(A)
print(x)

[[12  4  7]
 [ 7  5  8]
 [ 3  6  9]]


In [6]:
A = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]
tran = [[0,0,0],
        [0,0,0],
        [0,0,0]]
for i in range(len(A)):
    for j in range(len(A[0])):
        tran[i][j] = A[j][i]
print(tran)
        

[[12, 4, 7], [7, 5, 8], [3, 6, 9]]


In [10]:
# getting the kth column 
a= [[4, 5, 6], [8, 1, 10], [7, 12, 5]]
k=1
for i in range(len(a)):
    print(a[i][k])
        

5
1
12


In [14]:
# leet code
list = [int(i) for i in input().split()]
k = int(input())
list1 = []
list1.extend(list)
sum  = 0
l = len(list1)
for i in range(k):
    for j in range(l,l-k,-1):
        if list[i]>list1[j]:
            sum+=list[i]
            list = list.pop[i]
        elif list[i]<list1[j]:
            sum+=list1[j]
            list1 = list1.pop[j]
        elif list[i]==list1[j]:
            if i+1<l and j>0:
            if list[i+1]>list1[j-1]:
                sum+=list[i]
                list = list.pop[i]
            else:
                sum+=list1[j]
                list1 = list1.pop[j]
        else:
            print("hindustan jindabad")
print(sum)
            
        

3 4 5 6 7 8 5 4 3 
3


IndexError: list index out of range

In [18]:
# leet code
list = [11,49,100,20,86,29,72]
k = 4
list1 = []
list1.extend(list)
sum  = 0
for i in range(k):
    for j in range(len(list),l-k,-1):
        if list[i]>list1[j]:
            sum+=list[i]
            list = list1.pop[i]
        elif list[i]<list1[j]:
            sum+=list1[j]
            list1 = list1.pop[j]
        else:
            print("hindustan jindabad")
print(sum)
            
        

IndexError: list index out of range

In [20]:
list = [11,49,100,20,86,29,72]
k = 4
sum=0
for i in range(k):
    l=len(list)
    if list[0]>list[l-1]:
        sum=sum+list[0]
        list.pop(0)
    else:
        sum=sum+list[l-1]
        list.pop(l-1)
print(sum)

207


In [ ]:
# input of a matrix
row = int(input())
col = int(input())
matrix = [[int(input()) for i in range(col)] for j in range(row)]

In [ ]:
row = int(input())
col = int(input())
matrix = [[int(input()) for i in range(col)] for j in range(row)]

In [ ]:
row = int(input())
col = int(input())
matrix1= [[int(input()) for i in range(col)] for j in range(row)]
matrix2 = [[int(input()) for i in range(col)] for j in range(row)]
result = 0
for i in range(len(matrix1)):
    for j in range(len(matrix2[0])):
        for k in range(len(matrix2)):
            result[i][j] = result[i][j] + matrix1[i][j]*matrix2[k][j]
for r in result:
    print(r)
    
            
        