In [2]:
import numpy as np


In [2]:
mx_1s = np.array([1,1,1])
print(mx_1s)

[1 1 1]


In [3]:
mx_1s = np.array([[1,1,1],[1,1,1],[1,1,1]])
print(mx_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [4]:
mx_1s.dtype

dtype('int32')

In [5]:
mx_1s = np.ones((3,4), dtype = int)
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [4]:

 mx_0s = np.ones((4,3),dtype = bool)
print(mx_0s)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [7]:
mx_0s = np.zeros((4,3),dtype = str)
print(mx_0s)

[['' '' '']
 ['' '' '']
 ['' '' '']
 ['' '' '']]


In [8]:
em_str = ''
print(bool(em_str))


False


In [9]:
mx_em = np.empty((4,3))
print(mx_em)

[[1.48545158e-312 0.00000000e+000 8.76794447e+252]
 [2.15895723e+227 6.48224638e+170 3.67145870e+228]
 [4.51796771e-144 6.06003395e+233 1.06400250e+248]
 [2.26822459e+161 2.89847616e+131 1.58560488e-319]]


In [10]:
mx_em = np.empty((4,3), dtype = int)
print(mx_em)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


# 