# numpy functios

In [1]:
import numpy as np

# arange

In [2]:
#np.arange(start,end,steps)
arr_1d = np.arange(1,13)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [3]:
even_arr = np.arange(1,13,2)
print(even_arr)

[ 1  3  5  7  9 11]


# linespace()

In [4]:
 np.linspace(1,5,3)
    
    

array([1., 3., 5.])

# reshape()

In [5]:

arr_2d = arr_1d.reshape(2,6)
print(arr_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [6]:
arr_2d = arr_1d.reshape(3,4)
print(arr_2d)




[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
arr_3d = arr_1d.reshape(2,3,2)
print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# ravel()

In [8]:
arr_2d.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
arr_2d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
arr_2d.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])