# numpy random functions 

In [12]:
import numpy as np
import random

In [13]:
np.random.random(1)# random funtion will give value between 0 and 1 as default

array([0.43973043])

In [14]:
np.random.random((3,3))

array([[0.13840343, 0.27484009, 0.36895075],
       [0.18511722, 0.80897152, 0.72039887],
       [0.32094913, 0.22965013, 0.54020516]])

In [15]:
np.random.randint(1,4,(3,3)) # randomint function provides integer value

array([[2, 2, 3],
       [3, 3, 1],
       [2, 3, 3]])

In [16]:
np.random.rand(3)

array([0.55664939, 0.41227833, 0.81587151])

In [17]:
np.random.rand(3,3)

array([[0.59757929, 0.18286659, 0.40538121],
       [0.54273122, 0.71363864, 0.27605763],
       [0.7031693 , 0.12669112, 0.85434337]])

In [18]:
np.random.randn(3,3)

array([[ 0.95230235,  0.50713453, -0.917385  ],
       [ 1.74705777, -0.35524327,  0.91370535],
       [-0.01430448,  1.25662937,  1.42806659]])

In [19]:
x = [1,2,3,4,5]
np.random.choice(x)

4

In [20]:
np.random.choice(x)

4

In [21]:
for i in range(20):
 print(np.random.choice(x))
    

5
5
3
4
5
5
5
1
2
5
2
5
5
1
3
4
4
3
1
3


In [22]:
np.random.permutation(x)

array([4, 5, 1, 3, 2])